PREFIX ond: <https://data.meemoo.be/terms/ond/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?id ?label ?definition
WHERE {{
    BIND(URI('{concept}') AS ?concept)
    ?concept skos:narrower ?id.

    ?id a skos:Concept;
    skos:prefLabel ?label.

    OPTIONAL {{
        ?id skos:definition ?definition .
    }}
}}