PREFIX ond: <https://data.meemoo.be/terms/ond/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?id ?label ?definition
WHERE {{
    ?id a skos:Concept;
    skos:prefLabel ?label;
    skos:inScheme ond:vak;
    skos:related ?thema, ?graad.
    
    ?thema skos:inScheme ond:themas.
    ond:graad skos:member ?graad.

    OPTIONAL {{
        ?id skos:definition ?definition .
    }}

    FILTER (
        ?thema IN ({themas}) && 
        ?graad IN ({graden}) )

}}